import mongoose from "mongoose";

const invoiceSchema = new mongoose.Schema(
  {
    invoiceNumber: {
      type: String,
      required: false,
      unique: true,
      index: true,
    },

    // Invoice Type
    type: {
      type: String,
      enum: ["customer_order", "vendor_request", "inventory_receipt", "supplier_sale"],
      required: true,
    },

    // Related Entity Reference
    relatedEntity: {
      entityType: {
        type: String,
        enum: ["order", "vendor_request", "vendor_inventory"],
        required: true,
      },
      entityId: {
        type: mongoose.Schema.Types.ObjectId,
        required: true,
        refPath: "relatedEntity.entityType",
      },
    },

    // Parties (from → to)
    from: {
      userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
        required: true,
      },
      name: String,
      companyName: String,
      email: String,
      phone: String,
      address: {
        street: String,
        city: String,
        state: String,
        country: String,
        postalCode: String,
      },
      walletAddress: String,
    },

    to: {
      userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
        required: true,
      },
      name: String,
      companyName: String,
      email: String,
      phone: String,
      address: {
        street: String,
        city: String,
        state: String,
        country: String,
        postalCode: String,
      },
      walletAddress: String,
    },

    // Invoice Items
    items: [
      {
        description: {
          type: String,
          required: true,
        },
        quantity: {
          type: Number,
          required: true,
        },
        unit: String,
        pricePerUnit: {
          type: Number,
          required: true,
        },
        subtotal: {
          type: Number,
          required: true,
        },
      },
    ],

    // Financial Details
    subtotal: {
      type: Number,
      required: true,
    },
    tax: {
      type: Number,
      default: 0,
    },
    shipping: {
      type: Number,
      default: 0,
    },
    discount: {
      type: Number,
      default: 0,
    },
    total: {
      type: Number,
      required: true,
    },
    currency: {
      type: String,
      default: "CVT",
    },

    // Payment Details
    paymentStatus: {
      type: String,
      enum: ["paid", "pending", "partial", "refunded"],
      default: "paid",
    },
    paymentMethod: String,
    paymentDate: Date,
    transactionHash: String,  // Blockchain transaction hash for payment

    // Dates
    issueDate: {
      type: Date,
      required: true,
      default: Date.now,
    },
    dueDate: Date,

    // Notes
    notes: String,
    terms: String,

    // File Storage
    ipfsHash: {
      type: String,
      index: true,
    },
    ipfsUrl: String,
    localFilePath: String,  // Temporary local path before IPFS upload

    // Blockchain Verification
    blockchain: {
      verified: {
        type: Boolean,
        default: false,
      },
      txId: String,
      recordedAt: Date,
    },

    // Status
    status: {
      type: String,
      enum: ["draft", "issued", "sent", "paid", "cancelled"],
      default: "issued",
    },

    // Auto-generation flag
    autoGenerated: {
      type: Boolean,
      default: true,
    },
  },
  {
    timestamps: true,
  }
);

// Indexes
invoiceSchema.index({ "relatedEntity.entityId": 1 });
invoiceSchema.index({ "from.userId": 1 });
invoiceSchema.index({ "to.userId": 1 });
invoiceSchema.index({ type: 1, status: 1 });
invoiceSchema.index({ issueDate: -1 });

// Generate invoice number
invoiceSchema.pre("save", async function (next) {
  if (!this.invoiceNumber) {
    const prefix = {
      customer_order: "INV",
      vendor_request: "PUR",
      inventory_receipt: "REC",
      supplier_sale: "SAL",
    }[this.type];

    const count = await mongoose.model("Invoice").countDocuments();
    const number = String(count + 1).padStart(6, "0");
    const year = new Date().getFullYear();

    this.invoiceNumber = `${prefix}-${year}-${number}`;
  }
  next();
});

const Invoice = mongoose.model("Invoice", invoiceSchema);

export default Invoice;
